apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-env
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
